### ISSUE TITLE
down speed is too slow

### ISSUE THREAD

**Issue by bk201sama** [GKuChan/newbieTraining#51]
https://launchpadlibrarian.net/24493586/employees_db-full-1.0.6.tar.bz2 
Speed is very slow. Anyone have the problem?

**Comment by wxygeek** [comment]
我在百度云上传了一份，也许能帮到你：链接: http://pan.baidu.com/s/1sjDkG1Z 密码: iyrq

**Comment by bk201sama** [comment]
Thanks   :)
